### ISSUE TITLE
Select a template dependent on the data item.

### ISSUE THREAD

**Issue by gabipetrovay** [adioo/view#10]
This module can render an array of items. But some items in the array might require another fragment to be rendered based on some key values (or a computation with them).

Example:

a list of a git repo branches can be rendered like this:

``` html
<a href="#" class="branch" data-action="activate">{name}</a> <a href="#" data-action="delete"><span class="octicon octicon-x"></span>
```

but an active branch would require a fragment like this:

``` html
<span class="branch">{name}</span>
```

In other template languages you can have constructs like:

``` jade
if branch.active
    <a href="#" class="branch" data-action="activate">{name}</a> <a href="#" data-action="delete"><span class="octicon octicon-x"></span>
else
    <span class="branch">{name}</span>
```

How can I build something similar with the view module (or in service in general)?

To achieve this with CSS is not trivial (is possiible)

**Comment by ottiker** [comment]
Just append a hidden class or similar to those element which should not be displayed. I think it's a bad idea to put logic in a template. Otherwise we must build a new render module, which can handle logic in templates. Btw. view supports [data handlers](https://github.com/adioo/view/blob/master/view.js#L115-L118) which the data can be altered, before is used by to render a template.

**Comment by gabipetrovay** [comment]
This hide method does not work when the DOM is completely different like in the above example (unless the entire DOM is duplicated, which is neither effective, nor programmer-friendly).

And about data handlers, is there an example? The code shows that it must be a function (which can not be configure in JSON).

**Comment by gabipetrovay** [comment]
Probably, specifying something like:

``` json
{
    "template": {
        "engine": "jade",
        "to": "...".
        "html": "..."
    }
}
```

would not be such a bad idea.

**Comment by ottiker** [comment]
The solution we have to implement is, to have multiple templates (HTML snippets). And a handler that can determine which template is used to render the current item.

**Comment by gabipetrovay** [comment]
Fixed in 218b6fcee76e3638bda6cf14633c9dde7dfd57cd

**Comment by IonicaBizau** [comment]
@gabipetrovay Let GitHub close this when #13 is merged. :smirk:

**Comment by gabipetrovay** [comment]
Yup, Adi also asked himself if there is already a pull request. I did not see it.
