### ISSUE TITLE
Take default html path from markup

### ISSUE THREAD

**Issue by IonicaBizau** [adioo/view#11]
So, we will only specify the `client.markup` array and the default value of `template.html` will be `client.markup[0]`.

**Comment by gabipetrovay** [comment]
:+1:

**Comment by gabipetrovay** [comment]
Under the authority of @adioo :stuck_out_tongue_winking_eye: 

`markup` and a template `html` are two completely different things. `markup` makes resources available on the client. `html` in a template is just a reference to them. A more advanced builder in service will automatically add it to `markup` when added to a template OR restrict the choice of `html` to resources loaded with `markup`.
