### ISSUE TITLE
Add delegated events support to extFlow

### ISSUE THREAD

**Issue by IonicaBizau** [adioo/view#2]
Currently it seems this is not supported.

**Comment by ottiker** [comment]
What you mean by "delegated" events?

**Comment by IonicaBizau** [comment]
http://stackoverflow.com/a/22041545/1420197

**Comment by ottiker** [comment]
I think this isn't a problem, cause the `render` method rewrites the DOM tree every time with `innerHTML` and then appends the DOM listeners to new created DOM elements. And where I see the need of "delegated" events, is when you create DOM elements dynamically with javascript. Cause then you have to append the DOM events to every newly created DOM element.

**Comment by IonicaBizau** [comment]
You're right! :+1: I though that the module that loaded the HTML is not view, but it wasn't true.
