### ISSUE TITLE
Collect "elements" from rendered html

### ISSUE THREAD

**Issue by ottiker** [adioo/view#3]
Create a specification to get "elements" from the rendered html. Which then can be easily used in the `extFlow` collection.
Example HTML data attribute:

``` html
<div data-element="myIdentifier"></div>
```

Example `extFlow` config:

``` json
{
    "in": "click",
    "element": "myIdentifier",
    "out": [{}]
}
```

This gives the benefit, that we don't have to select the DOM elements with a "id" or the "class" attribute. And a web designer can easily define the interactive elements. Also a module can have predefined elements, which a designer can use to connect the to the modules default functionality (`.service.json` default flow configs).

**Comment by lcristianiim** [comment]
This seems to be a nice feature. In this way the "id's" and "class" can be used mainly for design and "data-element" for functionality.

In this way if we will need to delete a class to modify the design we will not have to worry about breaking the sites functionality.

**Comment by ottiker** [comment]
Also when the detail forms of in the builder are implemented, we could create a list of available "elements". Then the user could simply select an "element", when he wants to create an `extFlow` config.
