### ISSUE TITLE
Render array of primitive values

### ISSUE THREAD

**Issue by gabipetrovay** [adioo/view#9]
If a DB or an API call returns an array of primitive types (i.e. ["Venus", "Mars", "Snickers"]) the module should be able to render this array as well.

**Comment by ottiker** [comment]
It is possible, by using a positional index in the dot notation path. `my.data.array.0` where zero is the index of the array.

**Comment by gabipetrovay** [comment]
so `{0}`, `{1}`, etc. are also valid?

**Comment by ottiker** [comment]
No I don't think so, cause you need a data key, that matches a data field (`<div>{datafield}</div>`). Maybe it could work, though I never tested it.

**Comment by gabipetrovay** [comment]
The data returned is just an array.

**Comment by ottiker** [comment]
If the render method gets an array as data, then the hole html template is rendered multiple times. Then I assume you want to render a list?

**Comment by gabipetrovay** [comment]
yes

**Comment by ottiker** [comment]
Then the array must contain objects. The render can not just take a string and knows where to render it, there must be a data key to match with the data field in the template.
Solution:

``` js
view.render([{name: "A"}, {name: "N"}])
```
